### PR TITLE
Issue #6: using django.forms.models.model_to_dict to convert instance values to dict

### PR DESCRIPTION
**Pull request by romgar**

### CODE REVIEW

**Comment by romgar** [comment]
What do you think about this PR ?

**Comment by smn** [comment]
I think this changed behaviour subtly, up until now we've not included related fields (foreign keys, many to manys etc...) and this would change that.

If we go ahead with this then we'd need to add tests to make sure we at least know how this changes things.

**Comment by romgar** [comment]
You are fully right...
And with an optional boolean parameter to is_dirty(), like 'check_relationships' ?

**Comment by smn** [comment]
Happy to review any contributed code for this.

**Comment by romgar** [comment]
Ok ! I will propose something soon.

**Pull request closed without merging**
