### PR TITLE
Check relationships

### PR DESCRIPTION
**Pull request by romgar**
Adding a parameter named `check_relationship` on `is_dirty` to check foreign keys and one-to-one fields updates.
Trying to solve problem from Issue #2 and Issue #6 , while trying not to change current behaviour (trying to improve Pull Requests #3 and #12 )
If this PR is accepted, we will need to improve README to talk about this `check_relationship` parameter.

### CODE REVIEW

**Comment by erichonkanen** [comment]
is the author still actively maintaining this?

**Comment by romgar** [comment]
He has said (Issue #6) that he was not actively maintaining this code.
I will try to spend some time to propose other stuff to improve it, and hope that he can review it.

**Comment by romgar** [comment]
If somebody has some comments about it, don't hesitate to tell me !
@smn , do you have some time soon to review it ?

**Comment by smn** [comment]
:+1: nice work

**Pull request merged**
