### PR TITLE
Check all model fields, not only local ones.

### PR DESCRIPTION
**Pull request by mitar**
Check all model fields, not only local ones.

### CODE REVIEW

**Comment by romgar** [comment]
Hey @mitar , PR #16 resolves what you were needing ?

**Comment by mitar** [comment]
Huh, this is blast from the past. @kostko, are we using this anywhere now?

**Comment by kostko** [comment]
@mitar Not that I can see, so unfortunately we can't test this anymore.

**Comment by romgar** [comment]
I close this PR then, because:

1. Your PR is changing dirtyfields behaviour, which can be troublesome for users that were used to dirtyfields default checking,
2. We have added a `check_relationship` parameter to manage foreign keys.

**Pull request closed without merging**
