### PR TITLE
add python3 to travis build

### PR DESCRIPTION
**Pull request by brennerm**

### CODE REVIEW

**Comment by brennerm** [comment]
Please do not merge yet.

**Comment by brennerm** [comment]
The build is working now with Python 3.4. Please have a look at my changes.
I don't know why pip3 doesn't install django when calling ```pip install -e .```, but installing it manually works.

**Comment by romgar** [comment]
If Django is not installed, it means that the `setup.py` is not correctly managed for py3. It would be interesting to know why, because it means that this app is maybe not correctly packaged for py3.

It's not a problem for now, as we only have Django as a dependency, and I can imagine that people that are using dirty-fields have previously installed Django. But it could be a problem in the future and I prefer spending time now to understand what exactly happens before merging your request.

**Comment by brennerm** [comment]
Alright, I will look into this.

**Comment by brennerm** [comment]
What's the status here?

**Comment by romgar** [comment]
I prefer list comprehension because:

1. People that are working with py2 could think that it's weird to use `list()` on something that is returning a `list`
2. Code is more readable/understandable. It's not obvious why we use `list()` (just a compatibility fix), and not obvious what does filter do with `None` parameter.

**Comment by brennerm** [comment]
Ok, I'll implement your suggestion.

**Comment by brennerm** [comment]
Please check again

**Comment by romgar** [comment]
Thanks a lot @brennerm for your contribution !

**Pull request merged**
